<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>filetypes</key>
    <array>
      <string>ps1</string>
      <string>psm1</string>
      <string>psd1</string>
    </array>
    <key>name</key>
    <string>PowerShell</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Stop parsing</string>
        <key>begin</key>
        <string>(--%)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#lineComment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(.)</string>
            <key>name</key>
            <string>source.powershell</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#lineComment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#blockComment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#stringSingleQuoted</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#stringDoubleQuoted</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#arrayDeclaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#hashTable</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#scriptBlock</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#subExpression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variable</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#controlWords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#executableFiles</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>lineComment</key>
      <dict>
        <key>comment</key>
        <string>Line comment - must start with new line or at least one whitespace character before the '#'.</string>
        <key>begin</key>
        <string>(^#|\s#)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line</string>
      </dict>
      <key>blockComment</key>
      <dict>
        <key>begin</key>
        <string>(&lt;#)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(#&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block</string>
      </dict>
      <key>stringEscapeChars</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>(`[0abfnrtv"'$`])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
            <key>match</key>
            <string>("")</string>
          </dict>
        </array>
      </dict>
      <key>stringSingleQuoted</key>
      <dict>
        <key>begin</key>
        <string>((?&lt;!')')</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>('(?!'))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.single</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringSingleQuotedEscape</string>
          </dict>
        </array>
      </dict>
      <key>stringSingleQuotedEscape</key>
      <dict>
        <key>match</key>
        <string>(')(?:')</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
          </dict>
        </dict>
      </dict>
      <key>stringDoubleQuoted</key>
      <dict>
        <key>begin</key>
        <string>((?&lt;!\")\")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\"(?!\"))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringEscapeChars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variableWithoutPropertyHighlighting</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#subExpression</string>
          </dict>
        </array>
      </dict>
      <key>controlWords</key>
      <dict>
        <key>match</key>
        <string>(\b(?&lt;!-|\$)(?i:begin|process|exit|break|return|catch|finally|for|continue|foreach|throw|from|trap|try|do|if|until|in|using|else|elseif|while|end|where)\b(?!-|\.))</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <key>executableFiles</key>
      <dict>
        <key>comment</key>
        <string>Executable files, like exe, com, cmd and bat</string>
        <key>match</key>
        <string>(\b(([\p{L}A-Za-z0-9\-_\.]+).(?i:exe|com|cmd|bat))\b)</string>
        <key>name</key>
        <string>support.executable</string>
      </dict>
      <key>arrayDeclaration</key>
      <dict>
        <key>begin</key>
        <string>(\@?\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))(\.)*(([\w"']+)*)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.array</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>hashTable</key>
      <dict>
        <key>begin</key>
        <string>(@\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.hashtable</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>scriptBlock</key>
      <dict>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.scriptblock</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>subExpression</key>
      <dict>
        <key>begin</key>
        <string>(\$\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.subexpression</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>Invalid variable name</string>
            <key>match</key>
            <string>(\$)(\w+-\w+)\b</string>
            <key>name</key>
            <string>invalid.illegal</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.language</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>Automatic variables - read-only.</string>
            <key>match</key>
            <string>(\$)(?i:(_|args|consolefilename|error|event|eventsubscriber|executioncontext|false|foreach|home|host|input|lastexitcode|matches|myinvocation|nestedpromptlevel|null|pid|psboundparameters|pscmdlet|psculture|psdebugcontext|pshome|psitem|psscriptroot|psuiculture|psversiontable|pwd|sender|shellid|sourceargs|sourceeventargs|switch|this|true))\b(\.)*(([\w"'\- @#]+)*)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.variable</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.scope</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>$var, $local:var</string>
            <key>match</key>
            <string>(\$)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(\w+)(:\w+)?((\.[\w"'\- @#]+)*)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.scope</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>${var}, ${script:var}</string>
            <key>match</key>
            <string>(\$)(\{)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(.+?)(\})(\.)*(([\w"'\- @#]+)*)</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.powershell</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>Splatting</string>
            <key>match</key>
            <string>(@)(\w+)</string>
          </dict>
        </array>
      </dict>
      <key>variableWithoutPropertyHighlighting</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>Invalid variable name</string>
            <key>match</key>
            <string>(\$)(\w+-\w+)\b</string>
            <key>name</key>
            <string>invalid.illegal.powershell</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.powershell</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.language.powershell</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>Automatic variables - read-only.</string>
            <key>match</key>
            <string>(\$)(?i:(_|args|consolefilename|error|event|eventsubscriber|executioncontext|false|foreach|home|host|input|lastexitcode|matches|myinvocation|nestedpromptlevel|null|pid|psboundparameters|pscmdlet|psculture|psdebugcontext|pshome|psitem|psscriptroot|psuiculture|psversiontable|pwd|sender|shellid|sourceargs|sourceeventargs|switch|this|true))\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.powershell</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.scope.powershell</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.powershell</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.powershell</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>$var, $local:var</string>
            <key>match</key>
            <string>(\$)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(\w+)(:\w+)?</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.powershell</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.powershell</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.scope.powershell</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.powershell</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.other.powershell</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>${var}, ${script:var}</string>
            <key>match</key>
            <string>(\$)(\{)((?i:global|local|script|private|using|env|function|alias|cert|variable|hkcu|hklm|wsman):)?(.+?)(\})</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.powershell</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.powershell</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>Splatting</string>
            <key>match</key>
            <string>(@)(\w+)</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.powershell</string>
    <key>uuid</key>
    <string>3af8c7dd-6c15-40d4-a28b-c6a3105a39c7</string>
  </dict>
</plist>